version: '3'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://db:3306/testdb
      - DB_USERNAME=root
      - DB_PASSWORD=password
    depends_on:
      - db
    networks:
      - demo-network
    volumes:
      - ./storage/pi:/app/data/profile_images
      - ./storage/fi:/app/data/funding_image
      - ./storage/pd:/app/data/project_document
      - ./storage/si:/app/data/story_image
      - ./.env:/app/src/resources/.env

  db:
    build: ./db
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    volumes:
      - db_test:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    networks:
      - demo-network

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - demo-network
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/usr/share/nginx/html;

networks:
  demo-network:
    driver: bridge

volumes:
  db_test:
