name: Deploy React App and Services to EC2 using AWS SSM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. AWS CLI 환경 설정
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.EC2_REGION }}

      # 2. 환경 변수 설정
      - name: Set Environment Variables
        run: |
          echo "USER_NAME=${{ secrets.USER_NAME }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.TOKEN }}" >> $GITHUB_ENV

      # 3. 리포지토리 및 서브모듈 체크아웃
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
          submodules: recursive

      # 4. React 빌드 및 압축
      - name: Build React App
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install and Build
        run: |
          cd frontend
          npm install
          npm run build

      - name: Verify Build Output and Compress
        run: |
          if [ ! -d "frontend/build" ]; then
            echo "Build directory does not exist. Build failed."
            exit 1
          fi
          tar -czf frontend/build.tar.gz -C frontend build

      # 5. 빌드 파일을 EC2로 업로드
      - name: Upload Build to EC2 via SSM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          FILE_CONTENT=$(base64 frontend/build.tar.gz | tr -d '\n')
          echo "Uploading build file..."
          aws ssm send-command \
            --targets "Key=instanceIds,Values=${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":[
              "echo $FILE_CONTENT | base64 -d > /tmp/build.tar.gz"
            ]}' \
            --comment "Uploading React build file via SSM"

      # 6. EC2에서 스크립트 실행
      - name: Execute Deployment Script on EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --targets "Key=instanceIds,Values=${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":[
              "export USER_NAME=${{ secrets.USER_NAME }}",
              "export TOKEN=${{ secrets.TOKEN }}",
              "cd '${{ secrets.EC2_PROJECT_DIR }}'",
              "bash script.sh"
            ]}' \
            --comment "Deploy services and frontend" \
            --query "Command.CommandId" \
            --output text)
          echo "COMMAND_ID=$COMMAND_ID" >> $GITHUB_ENV

      # 7. 명령 상태 확인
      - name: Wait for command to finish
        run: |
          STATUS="InProgress"
          while [ "$STATUS" == "InProgress" ]; do
            echo "Checking command status..."
            STATUS=$(aws ssm get-command-invocation \
              --command-id ${{ env.COMMAND_ID }} \
              --instance-id ${{ secrets.EC2_INSTANCE_ID }} \
              --query "Status" \
              --output text)
            echo "Current status: $STATUS"
            sleep 5
          done

          if [ "$STATUS" != "Success" ]; then
            echo "Command failed with status: $STATUS"
            exit 1
          else
            echo "Command succeeded with status: $STATUS"
          fi
