name: Deploy React App and Services to EC2 using AWS SSM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. AWS CLI 환경 설정
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.EC2_REGION }}

      # 2. 리포지토리 및 서브모듈 체크아웃
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # 3. Node.js 환경 설정 및 React 빌드
      - name: Build React App
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install and Build
        run: |
          cd frontend
          npm install
          npm run build
          tar -czf build.tar.gz build

      # 4. 빌드 파일을 EC2로 업로드
      - name: Upload Build to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_PUB_IP }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > /tmp/ssh_key.pem
          chmod 400 /tmp/ssh_key.pem
          scp -o StrictHostKeyChecking=no -i /tmp/ssh_key.pem frontend/build.tar.gz $EC2_USER@$EC2_HOST:/tmp/
          rm -f /tmp/ssh_key

      # 5. EC2에서 스크립트 실행
      - name: Execute Deployment Script on EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --targets "Key=instanceIds,Values=${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":[
              "cd '${{ secrets.EC2_PROJECT_DIR }}'",
              "bash script.sh"
            ]}' \
            --comment "Deploy services and frontend" \
            --query "Command.CommandId" \
            --output text)
          echo "COMMAND_ID=$COMMAND_ID" >> $GITHUB_ENV

      # 6. 명령 상태 확인
      - name: Wait for command to finish
        run: |
          STATUS="InProgress"
          while [ "$STATUS" == "InProgress" ]; do
            echo "Checking command status..."
            STATUS=$(aws ssm get-command-invocation \
              --command-id ${{ env.COMMAND_ID }} \
              --instance-id ${{ secrets.EC2_INSTANCE_ID }} \
              --query "Status" \
              --output text)
            echo "Current status: $STATUS"
            sleep 5
          done

          if [ "$STATUS" != "Success" ]; then
            echo "Command failed with status: $STATUS"
            exit 1
          else
            echo "Command succeeded with status: $STATUS"
          fi

