name: Deploy Services to EC2 using AWS SSM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. AWS CLI 환경 설정
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.EC2_REGION }}

      # 2. 환경 변수 설정
      - name: Set Environment Variables
        run: |
          echo "USER_NAME=${{ secrets.USER_NAME }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.TOKEN }}" >> $GITHUB_ENV

      # 3. 스크립트 실행
      - name: Execute Deployment Script on EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --targets "Key=instanceIds,Values=${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":[
              "export USER_NAME=${{ secrets.USER_NAME }}",
              "export TOKEN=${{ secrets.TOKEN }}",
              "cd '${{ secrets.EC2_PROJECT_DIR }}'",
              "bash script.sh"
            ]}' \
            --comment "Deploy services" \
            --query "Command.CommandId" \
            --output text)
          echo "COMMAND_ID=$COMMAND_ID" >> $GITHUB_ENV

      # 4. 명령 상태 확인
      - name: Wait for command to finish
        run: |
          STATUS="InProgress"
          while [ "$STATUS" == "InProgress" ]; do
            echo "Checking command status..."
            STATUS=$(aws ssm get-command-invocation \
              --command-id ${{ env.COMMAND_ID }} \
              --instance-id ${{ secrets.EC2_INSTANCE_ID }} \
              --query "Status" \
              --output text)
            echo "Current status: $STATUS"
            sleep 5
          done

          if [ "$STATUS" != "Success" ]; then
            echo "Command failed with status: $STATUS"
            exit 1
          else
            echo "Command succeeded with status: $STATUS"
          fi
